### ISSUE TITLE
fix solaris build

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#110]
Looks fairly painless to install Solaris on regular hardware, https://www.oracle.com/technetwork/systems/hands-on-labs/s11-vbox-install-1408628.html

**Comment by RMKirkpatrick** [comment]
If Solaris support is something we really want, I'd prefer we made a priority of first supporting an active fork of OpenSolaris, e.g. [Illumos](https://wiki.illumos.org/display/illumos/illumos+Home).  If we can get it working on one of them, that may solve what the problem is on Oracle Solaris.

In any event, it's not as though Solaris users are completely out-of-luck.  A Solaris user who wants to use OpenMx can run the Linux R binary in a [jail](https://docs.oracle.com/cd/E37838_01/html/E61037/zonesoverview.html#scrolltoc).

**Comment by mcneale** [comment]
I agree, but what I would like to see is no ERROR! signals in the CRAN build reports.  We are professional programmers and hopefully this isn't a big task.  I do not want to sink much effort into it, and want to cap at a few hours' preliminary investigation.

Zones sound fine and all, but I have to say it felt good to get rid of Parallels software on my mac.  I have better things to do with disk space than to fill it up with additional operating systems that also slow everything else down when being run.  

I agree that this issue seems more of publicity exercise than one of tremendous utility to the modeling community, few of whom seem to use Solaris.   However, sometimes fixing corner case issues on other platforms can reap benefits elsewhere.  We won't know until we look.  Plus CRAN takes us a bit more seriously if we aren't failing on multiple platforms.  Solaris is the only one still with issues.

**Comment by mcneale** [comment]
Hmmm so we could offer getOpenMx.R for Solaris systems if we can be bothered to build and stash them on the server, same  as we do for NPSOL versions.  

If you are on Solaris and try to build from source on CRAN, does that break the binary?  Perhaps that would give a sign as to where in the code the CRAN build bombs.

**Comment by RMKirkpatrick** [comment]
Not planned; Solaris is dead.
