### ISSUE TITLE
Bug in mxAutoStart()

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#142]
[190221--autostart.R.txt](https://github.com/OpenMx/OpenMx/files/2891055/190221--autostart.R.txt)

See the attached script.  It starts off by constructing ["iloo's model"](https://openmx.ssri.psu.edu/thread/4198), and then tries to use `mxAutoStart()` on it.  But `mxAutoStart()` fails, with 

> Error: Unknown expected covariance name 'SimpMod.eC' detected in the expectation function of model 'Datmod'

Does `mxAutoStart()` assume something that doesn't actually apply in this case?

**Comment by mcneale** [comment]
I could reproduce the error.  The problem seems a bit gnarly.   With mxTryHard(model) it does worse than simple mxRun() (-2lnL of 62200 vs 62123) which  .  I think we should change the behavior of mxTryHard() to first try the user's starting values, then try the random starting values.  If that **is** what it does, then there may be a bug in reporting the best fitting model.

I tried upping the integration precision and using mxTryHardOrdinal.  It didn't help a lot although at least the SEs were reported (despite non-pd Hessian).  It was, however, happy with the solution, which is quite a bit better 61627.22 - though with different integration precision we likely aren't comparing apples with apples here.

Finally, I note that mxTryHardOrdinal does not report the total timings - summary of the final model is just the timing for that run.  It's probably not a good idea to change summary() behavior, but perhaps mxTryHard() could report the total timings when it does pop up a solution.

> mxOption(model,"mvnRelEps")
[1] 1e-06
> summary(modRun<-mxTryHard(model))
Beginning initial fit attempt
> summary(modRun<-mxTryHardOrdinal(model))
                                                                                 
Solution found!  Final fit=63810.063 (started at 63810.406)  (11 attempt(s): 11 valid, 0 errors)

Summary of SimpMod 
 
free parameters:
              name matrix row col  Estimate   Std.Error A lbound ubound
1  SimpMod.eC[1,2]     eC  x1  x2 0.7586449 0.004833140        0   0.99
2  SimpMod.eC[1,3]     eC  x1  x3 0.2362079 0.003814214 !      0   0.99
3  SimpMod.eC[2,3]     eC  x2  x3 0.3095144 0.004641330        0   0.99
4  SimpMod.eC[1,4]     eC  x1  x4 0.2954870 0.004082528 !      0   0.99
5  SimpMod.eC[2,4]     eC  x2  x4 0.2855600 0.004005912        0   0.99
6  SimpMod.eC[3,4]     eC  x3  x4 0.7615865 0.005399327        0   0.99
7  SimpMod.eT[1,1]     eT   1  x1 3.2269860 0.009383613                
8  SimpMod.eT[1,2]     eT   1  x2 3.2196408 0.007448213                
9  SimpMod.eT[1,3]     eT   1  x3 3.2200786 0.007565731                
10 SimpMod.eT[1,4]     eT   1  x4 3.2309320 0.008114534                

Model Statistics: 
               |  Parameters  |  Degrees of Freedom  |  Fit (-2lnL units)
       Model:             10                6414494              63810.06
   Saturated:             14                6414490                    NA
Independence:              8                6414496                    NA
Number of observations/statistics: 1603626/6414504


** Information matrix is not positive definite (not at a candidate optimum).
  Be suspicious of these results. At minimum, do not trust the standard errors.

Information Criteria: 
      |  df Penalty  |  Parameters Penalty  |  Sample-Size Adjusted
AIC:      -12765178               63830.06                 63830.06
BIC:      -91585055               63952.94                 63921.16
To get additional fit indices, see help(mxRefModels)
timestamp: 2019-02-22 13:09:36 
Wall clock time: 103.7583 secs 
optimizer:  CSOLNP 
OpenMx version number: 2.12.1 
Need help?  See help(mxSummary)

**Comment by RMKirkpatrick** [comment]
@mcneale Have you forgotten about [iloo's model](https://openmx.ssri.psu.edu/thread/4198)?  The whole point is that it's an extremely simple model for 4 binary-threshold variables from a huge dataset with very low prevalences, and is extremely difficult to optimize.

> With mxTryHard(model) it does worse than simple mxRun() (-2lnL of 62200 vs 62123) which . I think we should change the behavior of mxTryHard() to first try the user's starting values, then try the random starting values. If that **is** what it does, then there may be a bug in reporting the best fitting model.

It does indeed first try the user's start values, and what you report here is not necessarily evidence of a bug, because `mxTryHard()`'s defaults aren't suitable for ordinal analyses.  Specifically: (1) if the solution with fit 62123 had status Red, then by default `mxTryHard()` won't retain that solution; (2) `mxTryHard()` defaults to `fineTuneGradient=TRUE`, which is not helpful with ordinal analyses (indeed, I would say it's actually counterproductive).  That's why we have `mxTryHardOrdinal()`.

> Finally, I note that mxTryHardOrdinal does not report the total timings - summary of the final model is just the timing for that run. It's probably not a good idea to change summary() behavior, but perhaps mxTryHard() could report the total timings when it does pop up a solution.

Perhaps.  Note however that sometimes the time reported is actually the running time of the call to `mxRun()` that finds the solution plus the running time of the call to `mxRun()` to find the Hessian/SEs/CIs, if any.  See function `THFrankenmodel()` in R/MxTryHard.R.

**Comment by RMKirkpatrick** [comment]
Anyhow, for the sake of context: I decided to revisit iloo's model because I recently was able to use my Nelder-Mead implementation to diagnose convergence difficulties I had with a real-data mxGREML analysis.  Consequently, I felt I had gained a deeper intuition about how Nelder-Mead could be used on optimization problems that give the gradient-based optimizers trouble.

The attached script sets the mvnRelEps to 0.001, and attempts iloo's model once with CSOLNP, and once with Nelder-Mead.  Both attempts use
`mxTryHardOrdinal(model, silent=F, scale=0.05, extraTries=30)`
.  Both attempts get status Red, with a lot of missing SEs.  But Nelder-Mead reaches a fit value of 60879.58, whereas CSOLNP reaches a fit value of 61179.33.

[iloo_model_with_NelderMead--190219.R.txt](https://github.com/OpenMx/OpenMx/files/2895506/iloo_model_with_NelderMead--190219.R.txt)
