### ISSUE TITLE
mxOption reset option failing silently? (let reset reset a named key/value pair to its default)

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#151]
```R
# 1. mvnRelEps *= 5
mxOption(NULL, key="mvnRelEps", value= mxOption(NULL, key="mvnRelEps")*5)

#2. Now try and reset mvnRelEps to its default value?
mxOption(NULL, key="mvnRelEps", reset=TRUE)
[1] 0.025
```
The manual claims "When reset = TRUE, ‘key’ and ‘value’ are ignored.", but this is not true, it seems in fact that if key is set, reset is ignored...
Moreover, you have to provide a key...
```R
mxOption(NULL, reset=TRUE)
Error in mxOption(NULL, reset = TRUE) : 
  argument "key" is missing, with no default
```

A good fix would be
1. Don't require a key for mxOption(NULL, reset=TRUE), which would reset all options.
2. Add the behavior that, if `key` is set, then `reset = TRUE` will reset _that_ key....

**Comment by jpritikin** [comment]
mxOption has a really strange user interface. If you pass `reset=TRUE` then `key` and `value` are ignored (as documented). However, you still have to pass in a some key, even though it's ignored, because `key` isn't optional.

Regarding this issue, `reset=TRUE` with `model=NULL` was not implemented. Easy enough to fix, v2.12.2-125-gca3e86f55

**Comment by jpritikin** [comment]
> Add the behavior that, if key is set, then reset = TRUE will reset that key

Unfortunately, we can't do that because it could be incompatible with older code.

**Comment by jpritikin** [comment]
> Don't require a key for mxOption(NULL, reset=TRUE), which would reset all options.

Yeah, v2.12.2-126-g23d348687
