### ISSUE TITLE
.mxStandardizeRAMhelper sqrt(covParam[ifelse... NaNs produced

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#168]
`.mxStandardizeRAMhelper` generates a warning  which is obscure. Can this be coded better to avoid generating NaNs, suppressed, or caught and explained in helpful SEM-based terms?

```R
library(umx)

m1 = umxRAM("test", data=data.frame(x=rnorm(100)),
    umxPath("latent1", to = "latent1", arrows=1),
   umxPath(var= "x")
)
```
> 2: In sqrt(covParam[ifelse(is.na(out$label[i]), out$name[i], out$label[i]),  :  NaNs produced

**Comment by RMKirkpatrick** [comment]
What's your `mxVersion()`?  I can't reproduce that with the v2.12.2 release.

**Comment by tbates** [comment]
OpenMx version: 2.12.2.323 [GIT v2.12.2-323-g82b9565]
R version: R version 3.5.3 (2019-03-11)

**Comment by RMKirkpatrick** [comment]
OK, I can reproduce it with bleeding-edge OpenMx, but only with umx built from github.  The `NaN` is produced because the repeated-sampling covariance matrix of the point estimates has a negative diagonal element.  R _should_ warn if it's asked to take the `sqrt()` of a negative number.  Furthermore, the user will see the `NaN` SE in the output from `mxStandardizeRAMpaths()`; in the code  in the OP, they will see that 'latent1_to_latent1' has no SE in the table that's printed, and has an SE of `NA` when they run `summary()` on `m1`.

The current behavior is reasonable.  Maybe umx should detect `NaN`s in the output of `mxStandardizeRAMpaths()`?

**Comment by tbates** [comment]
Re-opening as I found where this raw code message to the user is generated by `OpenMx`. As raw code warnings lower user's confidence in the software, it would be valuable to trap these and turn them into either useful warning (or just step over the illegal operations - which is what happens anyway).

The R code reported as failing is located in `MxSE.R` and `MxSummary.R`

```R
# line 154 of MxSE.R & line 1164 of MxSummary.R
SEs <- sqrt(diag(covSparam))

# line 1175 in MxSummary.R
out$Raw.SE[i] <- sqrt(covParam[ifelse(is.na(out$label[i]),out$name[i],out$label[i]),
                                       ifelse(is.na(out$label[i]),out$name[i],out$label[i])])
```

`mxSE` and `summary` should perhaps check for NA or wrap these in try blocks?
