### ISSUE TITLE
Warning/error text: remove info that ordinary users can't understand

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#172]
Warnings and errors shouldn't contain information most ordinary users can't use.
In the first instance, we can  search for message strings like

1. "The Hessian at the solution does not appear to be convex?" could be:
> The model does not seem to be identified (at least at the current parameter estimates)
2. Replace code 5/6/10/RED with helpful info on the model problem, e.g.:
> "Model not-identified due to diagonal  of A being non-zero"
3. Additional checks to replace "Hessian says bad" with e.g.:
> You included a SINGLE-HEADED path from "latent X" to itself. Running mxCheckIdentification(model) may help to diagnose the problem.

see, e.g. fix for #169

**Comment by mhunter1** [comment]
I disagree with the _replacement_ suggestion.  Instead, I favor _adding_ further information if we have any.

In the case of 1, replacing

> The Hessian at the solution does not appear to be convex

with

> The model does not seem to be identified (at least at the current parameter estimates)

is simply not accurate.  There are many possible causes of the Hessian being non-convex.  Saying the model is not identified because the Hessian is non-convex is just misleading.

I agree that we should try to make all errors, warnings, and messages as comprehensible as we can while being accurate.  The difficulty of this task is why we haven't done it yet.
