### ISSUE TITLE
refModels = TRUE 

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#191]
Add refModel = TRUE control to increase workflow compatibility (e.g. genomic SEM) and ease life for the 95% of users who expect a run model to support the fit statistics they need 

`summary.MxModel(refModels = TRUE`)

`mxModel(..., refModels = c(FALSE|TRUE))` 

`mxRun(..., refModels = c(FALSE|TRUE))` 

_Originally posted by @tbates in https://github.com/OpenMx/OpenMx/issues/173#issuecomment-491950983_

**Comment by RMKirkpatrick** [comment]
Having given this some thought, I actually think the way it works now is the proper way.  If some fit indices are missing because one or both reference models are missing, `summary()`'s output directs users to the man page for `mxRefModels()`.  That's a good thing.  I've seen enough users naively apply `mxRefModels()` in cases for which the function was never designed, but the man page warns users about those cases.

**Comment by tbates** [comment]
Original rational was only speed, this new rationale means we should turn off ref models for cov data (ref models can be wrong for cov data too).

But... let’s just make a new issue to improve refmodels. Adding checks for the cases it may not be smart enough to do the right thing, and doing the right thing in more cases.

But it seems orthogonal to this issue, which is to allow the user to more readily do what we already tell them do across multiple steps.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mcneale** [comment]
Is this another case for better documentation?  With a sufficiently explicit example, anyone with R skills can get what they want.  And in this case the documentation [https://www.rdocumentation.org/packages/OpenMx/versions/2.12.2/topics/omxSaturatedModel](url) has just such an example.  Rob’s rationale makes sense to me; and indeed if we can detect better which cases are likely incorrect, it would be great.

**Comment by tbates** [comment]
OK. `umx` gives people what they need, so I'll close this as by design.
