### ISSUE TITLE
mxDataWLS and mxFitFunctionWLS: change default type to "DWLS"

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#208]
Currently mxDataWLS and mxFitFunctionWLS default to WLS. DWLS would be a better choice

`mxDataWLS(data, type = "WLS")`

`mxFitFunctionWLS(type=c('WLS','DWLS','ULS'), ...`

**Comment by jpritikin** [comment]
It's an easy change, but any concern about backward incompatibility?

**Comment by tbates** [comment]
Bit more relaxed given that people were saying "whatever the default is will be fine" and we're greatly improving it. I'd say `mxFitFunctionWLS` should be listed as experimental/interface-can-change category for reasons like this.

**Comment by jpritikin** [comment]
Hope nobody complains

**Comment by mcneale** [comment]
Why is DWLS a better choice?  Its statistical properties seem inferior to those of full WLS.

**Comment by tbates** [comment]
@mhunter1 and I reported that in simulations and real data, estimates with `WLS` were often far from those based on `ML` whereas `DWLS` values were typically close to the ML/true-simulated values.

My reading of comparisons suggests that compared to WLS, DWLS provides more accurate parameter estimates and is more robust. A practical issue is likely that DWLS is more suitable for small sample sizes/large models, and copes better with skew and with ordinal data.

Seeking empirical papers to inform one on this issue suggests that there aren't many, and all those I could see examined one or at most a small set of possible models…

**Comment by mcneale** [comment]
We should ALWAYS worry about 'invisible' backward compatibility issues with anything released.  I cannot see a good reason to switch to DWLS default.  In theory it has to be inferior statistically - otherwise it's like saying "we don't need to worry that twin 1 and twin 2 are not independent statistics, we'll just buy into reporting standard errors that are smaller than they should be.  Many an editor has whined about that.

Are the results of your simulations available?  How do they look wrt SEs?  Were the data MCAR, MAR or what?  Certain versions of 'what' (including departures from normality) could make MLEs inaccurate, and perhaps a poor yardstick.

**Comment by RMKirkpatrick** [comment]
It's only a backwards-incompatible change in the default behavior though.

FWIW, MPlus, lavaan, and GenomicSEM's wrapper to lavaan all default to DWLS.

**Comment by mcneale** [comment]
@RMKirkpatrick Hmm fair point.  DWLS is faster if less theoretically sound.

**Comment by RMKirkpatrick** [comment]
Whenever there's a backwards-incompatible change in defaults, I mention it as such in the release announcement.  When there's a backwards-incompatible change that cannot be overridden by the user choosing non-default arguments, I mention it in the release announcement **in bolded text**.

**Comment by mcneale** [comment]
I don't think that's sufficiently obvious to a user who's scratching their head because their results with  the same script and the same data now look totally different.   That erodes trust.  Many users will  not read release notes (and there might be years' worth of them to go through line by line).  

Anyone using the default (not providing an explicit argument type='DWLS' or whatever) should receive a note at run time and in summary that the default changed from WLS to DWLS at version 2.x.x and be  given instructions how to change it back in the call.

At the very least, it should be documented in ?mxData - likely the first place anyone confused will look.

**Comment by jpritikin** [comment]
> I don't think that's sufficiently obvious to a user who's scratching their head because their results with the same script and the same data now look totally different.

Another option is to not have a default. Require the user to pick which kind of WLS they want.

**Comment by tbates** [comment]
It's an important choice that the user should consciously make, which argued for no default

**Comment by jpritikin** [comment]
During the Jun 14 meeting, we decided to keep the default unchanged (WLS).
