### ISSUE TITLE
Check for NAs in definition variables (data.varName labels)

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#23]
IIRC, we used to check for NAs in definition variables and halt. But this isn't happening now. We should.

_Background_: I was getting odd results building a new model with algebras and definition variables. Everything looked OK, but the model was returning start values and code RED).

Turns out the issue is that the definition variables contained NAs, but the model didn't report this... no idea what it did when it hit them, in fact.

Here's a quick model which I think should trigger a **stop**("_definition vars 'data.wt2' can't have missing values..._") error.

NOTE: It turns out this toy model doesn't cause evaluation, so isn't a test case. See below for an actual test case.

```splus
require(umx)
data(twinData) # ?twinData from Australian twins.
fit1 = mxModel("fit1",
	mxMatrix(name="x", "Full", nrow=1, ncol=1, free=F, values=1),
	mxMatrix(name="def", "Full", nrow=1, ncol=1, free=F, labels= "data.wt2"),
	mxAlgebra(x %*% def, name="prod"),
	mxFitFunctionAlgebra("prod"),
	mxData(twinData[,"wt2", drop=F], type="raw")
)
# ====================
# = This should fail =
# ====================
fit1 = mxRun(fit1) 
# Because...
sum(complete.cases(twinData$wt2))
[1] 86

```

**Comment by mcneale** [comment]
In classic Mx, rows with NA for any definition variable were dropped - declaring variables as definition variables did this automatically.  However, I don’t know whether this behavior is inherent in OpenMx.  If it were (it’s not unreasonable) then I think it should be noted somewhere (summary? or during fitting) that x many rows of the data have been eliminated.  Number of statistics would be a bit too cryptic by itself.  Or simply stop and offer user syntax to clean out NA’s manually.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369  michael.neale@vcuhealth.org<mailto:michael.neale@vcuhealth.org>

On Aug 25, 2017, at 7:49 AM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


IIRC, we used to check for NAs in definition variables and halt. But this isn't happening now. We should.

Background: I was getting odd results building a new model with algebras and definition variables. Everything looked OK, but the model was returning start values and code RED).

Turns out the issue is that the definition variables contained NAs, but the model didn't report this... no idea what it did when it hit them, in fact.

Here's a quick model which I think should trigger a stop("definition vars 'data.wt2' can't have missing values...") error.

require(umx)
data(twinData) # ?twinData from Australian twins.
fit1 = mxModel("fit1",
        mxMatrix(name="x", "Full", nrow=1, ncol=1, free=F, values=1),
        mxMatrix(name="def", "Full", nrow=1, ncol=1, free=F, labels= "data.wt2"),
        mxAlgebra(x %*% def, name="prod"),
        mxFitFunctionAlgebra("prod"),
        mxData(twinData[,"wt2", drop=F], type="raw")
)
# ====================
# = This should fail =
# ====================
fit1 = mxRun(fit1)
# Because...
sum(complete.cases(twinData$wt2))
[1] 86

**Comment by tbates** [comment]
Where classic Mx dropped rows with  NA for any definition variable, OpenMx appears to be running with NAs in the rows, and not generating an error - just a badly fitting model.

e.g. from the example above, it appears that rows are not being dropped when def vars contain NA, and the model runs without issuing any messages, warnings, or errors.

```splus
    fit1$data$numObs
    [1] 3808
    sum(complete.cases(twinData$wt2))
    [1] 3722
```

I agree that if the rows can be dropped automagically, that is probably OK (with a note during mxRun that x many rows of data have been eliminated.)

**Comment by RMKirkpatrick** [comment]
When did we start allowing NAs on definition variables, and why?  I don't remember this ever having been discussed since I've been involved with the project.

In most cases, a definition variable is used to define the conditional value of a parameter on which the row loglikelihood depends (usually the mean), which causes the row to have a loglikelihood of NA, which in turn causes the total fit value to be NA, which in turn causes the optimizer to quit because the fitfunction evaluates to a non-finite result at the start values.  Even assuming there's a use-case justifying why NAs on definition variables don't lead to a fatal error, it seems niche enough to warrant throwing a warning.

Also, do parts of our backend code still use the unsafe BLAS?  If so, then allowing NAs on definition variables could lead to instances where zero times NA equals zero instead of NA, and NA is correct per IEEE standards for floating-point arithmetic.

**Comment by RMKirkpatrick** [comment]
> Here's a quick model which I think should trigger a stop("definition vars 'data.wt2' can't have missing values...") error.

For the specific case of this example model, I disagree.  First of all, this example model has no free parameters to optimize.  Secondly, even if it did, the definition variable will only cause the fitfunction to evaluate to NA if the wt2 variable happens to be NA in the last row of the internally sorted dataset.  What I think you're trying to do is going to require a "row algebra" acting on `filteredDataRow`, a "reduce algebra" acting on the row algebra, and an MxFitFunctionRow; see the help page for `mxFitFunctionRow`.

**Comment by jpritikin** [comment]
On Sat, Aug 26, 2017 at 02:00:08AM +0000, Steve email'd to the list:
> This was discussed extensively 5+ years ago.  We came to the conclusion that
> row-wise deletion based on definition variables was as bad as row-wise deletion
> based on any other variable.  It is my understanding that we are currently doing
> FIML estimation when definition variables have NAs.  So, what is done depends on
> the model.  If a definition variable clobbers the whole row, then that row
> doesn't contribute to the likelihood.  But to the extent that a row can be
> filtered and estimated, it is.  Yes, row wise deletion often improves model fit,
> but at the cost of potentially erroneous parameter estimates.

**Comment by RMKirkpatrick** [comment]
Yes, I saw Steve's email to the list.  When I first learned OpenMx, (five and a half years ago), running an MxModel with NAs on definition variables resulted in a fatal error, and I adopted a strategy for working around NAs on definition variables, which I have used ever since.  I joined the project four years ago, when v2.0 was in development, and I don't recall that we ever discussed changing OpenMx's behavior when there are NAs on definition variables (although I could be wrong).

I concur that row-wise deletion based on missing values on definition variables is not good design.  The default behavior ought to be a fatal error if NAs on definition variables are detected, with some way (an mxOption, or argument to `mxRun()`) of overriding the error if the user desires.  As Tim reported, and I described above, a typical result of NAs on definition variables is to make the optimizer quit because the fitfunction is NA at the start values, but with no hint to the user as to what the problem is.

I've been telling people for years that OpenMx doesn't tolerate NAs on definition variables.  It's a bit embarrassing to think that has changed, without my knowledge, and for no clear reason.

**Comment by jpritikin** [comment]
@RMKirkpatrick The purpose of copying Steve's email here was to make a complete record of the conversation. I was not implying that I agreed with his position.

I believe the next step in addressing this issue is to determine what OpenMx actually does. Is there evidence in the source code to support Steve's contention or do NA def vars only "work" by accident?

**Comment by SteveBoker** [comment]
My memory may be in error, if others do not remember this.

> On Aug 28, 2017, at 10:53 AM, Joshua Pritikin <notifications@github.com> wrote:
> 
> @RMKirkpatrick The purpose of copying Steve's email here was to make a complete record of the conversation. I was not implying that I agreed with his position.
> 
> I believe the next step in addressing this issue is to determine what OpenMx actually does. Is there evidence in the source code to support Steve's contention or do NA def vars only "work" by accident?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------------
Steven Boker
University of Virginia
Department of Psychology
(USPS) POB 400400; Charlottesville, VA 22904
(Package) Gilmer Hall 102; Charlottesville, VA 22903
Office: 434-243-7275  Cell: 434-249-0624  
 Skype: 434-218-1248   Fax: 434-243-4939
http://people.virginia.edu/~smb3u
http://faculty.virginia.edu/humandynamicslab
http://openmx.psyc.virginia.edu
----------------------------------------------------------

**Comment by RMKirkpatrick** [comment]
Steve: I bet you're remember correctly, except that it was longer ago than you think, like around when OpenMx was first being designed.  I say that because it was probably a deliberate design decision of the OpenMx team to handle NAs on definition variables differently from how classic Mx did it.

Anyhow, I wrote a script that modifies demo/UnivariateTwinAnalysis_MatrixRaw.R to use a definition variable with an NA.  The call to `mxRun()` ends with 'Error: NA value for a definition variable is Not Yet Implemented.'.  This error is thrown from the backend, apparently from a function in either src/omxData.cpp or src/omxExpectation.cpp .  My guess is that it's being thrown by `omxExpectation::loadDefVars()`, because Tim's simple example above doesn't trigger the error, and also doesn't use an expectation.  @tbates , could you provide more details about the real-world use case that prompted you to open this issue?

Anyhow, it appears that it is indeed possible to run an MxModel with NAs on definition variables without error, but trying to do so in many, perhaps most, cases will trigger an error.
[170829.R.txt](https://github.com/OpenMx/OpenMx/files/1261186/170829.R.txt)

**Comment by RMKirkpatrick** [comment]
Hmm, OK, so using an expectation versus not using one, and having free parameters versus not having them, don't seem to make a difference.  I'm attaching another script, which modifies models/passing/LAD--CheckCode6.R to have an NA on the definition variable.  The MxModel uses an MxFitFunctionRow, and no expectation.  Trying to run it ends with the 'NA value for a definition variable' error, even if it has no free parameters.
[170829a.R.txt](https://github.com/OpenMx/OpenMx/files/1261238/170829a.R.txt)

**Comment by RMKirkpatrick** [comment]
The two functions in the backend that can throw the 'NA value for a definition variable' are `omxData::loadDefVars()` (line 725 of src/omxData.cpp) and `omxExpectation::loadDefVars()` (line 285 of src/omxExpectation.cpp).  Both have an integer argument that appears to be a row number.  I suspect that our backend never checks for definition variables if it never has to do anything with them in a row-wise fashion.

I recompiled OpenMx to get debug logging from the backend, and ran Tim's example model from above.  It turns out that the algebra fitfunction only uses the first (not the last) value of the 'wt2' variable (which is 57) when calculating the fitfunction.  Because the backend never does anything repeatedly over all the rows of the dataset, it never checks for NAs on definition variables.

I'm attaching a script that uses an algebra fitfunction, and contains a raw dataset and an MxMatrix containing a definition variable, neither of which are actually used by the fitfunction.  It runs without error.

So, it seems as though we only check for NAs on definition variables when definition variables have to be loaded from each row of the dataset.  Is that acceptable?

Again, @tbates , I'm curious if you have a non-toy example similar to what you reported in the opening post, where NAs on definition variables didn't trigger an error and therefore led to optimization failure.
[170829b.R.txt](https://github.com/OpenMx/OpenMx/files/1261573/170829b.R.txt)

**Comment by tbates** [comment]
Here's a univariate ACE script [NA def test.R](http://openmx.ssri.psu.edu/sites/default/files/NA%20def%20test.R) which (line 6) allows you to toggle whether to delete or leave intact rows with missing def vars.

With NA rows deleted, it runs and returns correct results.

Retaining rows that have NA defvars, it runs, but returns the start values...

I get the same experience with all the models I've tried (all using OpenMx version number: 2.7.12, not sure how far back this reversion goes).

PS: I stumbled on this bit of excavated collective memory at the 2016 IBG question forum (what a great week!)

[question 3](https://ibg.colorado.edu/dokuwiki/doku.php?id=workshop:2016:questions) is relevant.
 
Scripts did not allow full or partial missingness in def vars, and we taught students to delete rows to save runtime errors requesting them to do so. Not sure what Mike meant about putting -999 in as a dummy value for cotwin vars of twins who were missing the def and DV variables.

**Comment by SteveBoker** [comment]
It may be that this was discussed but never implemented.  However, note that if you are using a definition variable as a moderator then a row with an NA in the definition variable should be treated as if all variables downstream from the moderator are missing as in a normal FIML case where those same downstream variables were NAs.  Rowwise deletion is not something we should be recommending when people are using definition variables as moderators unless the model is specified such that the downstream variables are all manifest variables in the model.

Of course, there are many other uses for definition variables other than moderators, but that is my own most likely use case.  

R never defaults to row-wise deletion, it halts if you do not specify what you want done with NAs.  I believe that is a good philosophy, although wearisome to users wishing for things to "just work".

Best,
Steve

> On Aug 29, 2017, at 4:07 PM, RMKirkpatrick <notifications@github.com> wrote:
> 
> The two functions in the backend that can throw the 'NA value for a definition variable' are omxData::loadDefVars() (line 725 of src/omxData.cpp) and omxExpectation::loadDefVars() (line 285 of src/omxExpectation.cpp). Both have an integer argument that appears to be a row number. I suspect that our backend never checks for definition variables if it never has to do anything with them in a row-wise fashion.
> 
> I recompiled OpenMx to get debug logging from the backend, and ran Tim's example model from above. It turns out that the algebra fitfunction only uses the first (not the last) value of the 'wt2' variable (which is 57) when calculating the fitfunction. Because the backend never does anything repeatedly over all the rows of the dataset, it never checks for NAs on definition variables.
> 
> I'm attaching a script that uses an algebra fitfunction, and contains a raw dataset and an MxMatrix containing a definition variable, neither of which are actually used by the fitfunction. It runs without error.
> 
> So, it seems as though we only check for NAs on definition variables when definition variables have to be loaded from each row of the dataset. Is that acceptable?
> 
> Again, @tbates , I'm curious if you have a non-toy example similar to what you reported in the opening post, where NAs on definition variables didn't trigger an error and therefore led to optimization failure.
> 170829b.R.txt
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------------
Steven Boker
University of Virginia
Department of Psychology
(USPS) POB 400400; Charlottesville, VA 22904
(Package) Gilmer Hall 102; Charlottesville, VA 22903
Office: 434-243-7275  Cell: 434-249-0624  
 Skype: 434-218-1248   Fax: 434-243-4939
http://people.virginia.edu/~smb3u
http://faculty.virginia.edu/humandynamicslab
http://openmx.psyc.virginia.edu
----------------------------------------------------------

**Comment by RMKirkpatrick** [comment]
> Not sure what Mike meant about putting -999 in as a dummy value for cotwin vars of twins who were missing the def and DV variables.

Suppose there are twin pairs in the sample where one twin has non-missing phenotype scores but has NAs on definition variables.  For those individuals, you replace their definition-variable NAs to some really out-of-range value like -999, and change their non-missing phenotype scores to NA.  If you do it correctly, then during FIML, OpenMx will "filter out" the missing phenotype scores from the data row, and never actually use the -999 value, and will still evaluate the likelihood of the co-twin with complete data.  If you do it incorrectly and the "pseudo-missing" -999 values get used in evaluating the likelihood, your results should look funny, clueing you in that something is wrong.  This trick has probably been independently discovered several times; I first learned it from Matt McGue while I was a grad student, in the context of working around classic Mx's total deletion of rows containing missing vales on definition variables.

**Comment by RMKirkpatrick** [comment]
> Here's a univariate ACE script NA def test.R which (line 6) allows you to toggle whether to delete or leave intact rows with missing def vars.

I reproduce the behavior you report, with OpenMx version 2.7.13.25 (looks like I need to update what the most recent tag is in my local repository).  Surprisingly, if you try it with `testNA` set to `TRUE` and with NPSOL set to the default optimizer, NPSOL actually moves away from the start values and reduces the fit from its initial value by 11 orders of magnitude.  The NA doesn't seem to necessarily propagate the way I thought it would; even when CSOLNP or SLSQP give back the start values, the backend returns a finite value for the fitfunction.

I note that the only row in either `mzData` or `dzData` that has a missing age value is row 42 of `dzData`.

**Comment by RMKirkpatrick** [comment]
If I run Tim's latest script and then add this:
`modelDZ2 = mxModel(
	"DZ", pars, defAge,
	mxAlgebra(name = "expMean", meanG + cbind(b%*%Age, b%*%Age)),
	mxAlgebra(0.5%x%A+ C, name="cDZ"),
	mxAlgebra(rbind(cbind(V, cDZ), cbind(t(cDZ), V)), name="expCovDZ"),
	mxData(dzData, type="raw"),
	mxExpectationNormal("expCovDZ", means="expMean", dimnames=selVars),
	mxFitFunctionML(vector=T)
)
foo <- mxRun(modelDZ2,useOptimizer=F)
foo$fitfunction$result[42]
mxEval(expMean,foo,T,defvar.row=42)`
I see that the -2logL for the row with the missing age evaluates to zero, but the conditional mean for that row is a vector of NAs.  Is the row-wise fitfunction supposed to evaluate to zero when it has NAs in its parameter vector??

**Comment by mcneale** [comment]
Makes sense to me - equivalent to dropping the record from the dataset.  Likelihood of 1, log-likelihood of zero is the same for every entirely missing row in the dataset, and effectively handles the definition variable problem without rearranging the dataset.  The BIG issue with this is that the number of statistics could change if a variable is vs. is not declared as a definition variable, and also if we change the model so that the definition variable affects the likelihood.  I don’t think automatically checking whether def vars actually have an impact on the likelihood of the model, was ever implemented, so perhaps it isn’t an issue.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369  michael.neale@vcuhealth.org<mailto:michael.neale@vcuhealth.org>

On Aug 30, 2017, at 6:00 PM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


If I run Tim's latest script and then add this:
modelDZ2 = mxModel( "DZ", pars, defAge, mxAlgebra(name = "expMean", meanG + cbind(b%*%Age, b%*%Age)), mxAlgebra(0.5%x%A+ C, name="cDZ"), mxAlgebra(rbind(cbind(V, cDZ), cbind(t(cDZ), V)), name="expCovDZ"), mxData(dzData, type="raw"), mxExpectationNormal("expCovDZ", means="expMean", dimnames=selVars), mxFitFunctionML(vector=T) ) foo <- mxRun(modelDZ2,useOptimizer=F) foo$fitfunction$result[42] mxEval(expMean,foo,T,defvar.row=42)
I see that the -2logL for the row with the missing age evaluates to zero, but the conditional mean for that row is a vector of NAs. Is the row-wise fitfunction supposed to evaluate to zero when it has NAs in its parameter vector??

**Comment by RMKirkpatrick** [comment]
So, here's what still needs to be resolved for this issue.

Sometimes OpenMx detects an NA value for a definition variable, and throws an error.  Other times, OpenMx apparently sets the row-loglikelihood of rows with NAs on definition variables to zero. In effect, that's silent row-wise deletion.  It also mysteriously interferes with the optimizer's progress.

1.  Why is the behavior inconsistent?  Answering this question is likely going to involve running Tim's test case under gdb.  Since the effective row-wise deletion also occurs with pathological optimizer behavior, my suspicion is that it's happening due to a bug.  That is, I don't think anyone's ever pushed a commit that tried to zero out rows with NA defvars deliberately.
2.  What is the desired behavior in the first place?  I'm very much of the opinion that NAs on defvars should result in a fatal error, not row-wise deletion.

**Comment by mcneale** [comment]
I think an error with as precise advice as possible on how to eliminate the rows in question is the way to go.  I’d be ok with automatic dropping data rows due to NA’s in definition variables, as long as a clear description of how many rows were eliminated (and % of the data).

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369  michael.neale@vcuhealth.org<mailto:michael.neale@vcuhealth.org>

On Aug 31, 2017, at 4:33 PM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


So, here's what still needs to be resolved for this issue.

Sometimes OpenMx detects an NA value for a definition variable, and throws an error. Other times, OpenMx apparently sets the row-loglikelihood of rows with NAs on definition variables to zero. In effect, that's silent row-wise deletion. It also mysteriously interferes with the optimizer's progress.

  1.  Why is the behavior inconsistent? Answering this question is likely going to involve running Tim's test case under gdb. Since the effective row-wise deletion also occurs with pathological optimizer behavior, my suspicion is that it's happening due to a bug. That is, I don't think anyone's ever pushed a commit that tried to zero out rows with NA defvars deliberately.
  2.  What is the desired behavior in the first place? I'm very much of the opinion that NAs on defvars should result in a fatal error, not row-wise deletion.

**Comment by jpritikin** [comment]
`twinData$age` is of type `integer`. I suspect our check for NA only considers type `double`.

**Comment by RMKirkpatrick** [comment]
> `twinData$age` is of type `integer`. I suspect our check for NA only considers type `double`.
I thought we cast all non-ordinal variables to double at some point in the handoff to the backend?

**Comment by jpritikin** [comment]
> I thought we cast all non-ordinal variables to double at some point in the handoff to the backend?

We did, before I rewrote the sorting code. This looks like a regression that is my fault. I'll fix it.

**Comment by jpritikin** [comment]
e3c0693f3907
