### ISSUE TITLE
two time points latent change score analysis

### ISSUE THREAD

**Issue by wanglu2014** [OpenMx/OpenMx#237]
There are data of two time points: before and after the dietary intervention. Follow the following hypothesis; we have been planing to carry out latent change score analysis. 
An example of our data has been attached, could you kindly provide the suggestion on model building for it? Both lavaan or openMx were good enough.
Thank you for your help!
![图片](https://user-images.githubusercontent.com/12541282/64680521-860f6800-d4b0-11e9-9db0-0be58cc52465.png)

[meta_toy.zip](https://github.com/OpenMx/OpenMx/files/3599736/meta_toy.zip)

**Comment by tbates** [comment]
Dear Wanglu, this is not an OpenMx feature request of problem report... It is a "how do I make model X in OpenMx" question. You need to post it on the OpenMx forums, not here.

PS: The picture you draw lacks boxes and circles: Need to specify it as a complete graphical model in order to receive meaningful help over on the forums
