### ISSUE TITLE
mxCompare() needs to know about different fit units

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#24]
The attached script (adapted from
   models/passing/IntroSEM-OneFactorCov.R ) fits a common-factor model to
   covariance-matrix data by ML, then fits a nested submodel to the same
   data by WLS, and compares the two fitted MxModel objects via
   mxCompare() .  The comparison is of course not valid, but mxCompare()
   does not complain.

   Similarly, comparisons involving the GREML fitfunction should use -2
   times the unrestricted loglikelihood (which is also returned to the
   frontend in the fitfunction object), not -2 times the restricted
   loglikelihood.

See [170818--bad_mxCompare.txt](https://github.com/OpenMx/OpenMx/files/1252019/170818--bad_mxCompare.txt)

**Comment by RMKirkpatrick** [comment]
I tried to make headway on this issue today.  It's going to be a little more tricky that I first thought, because most frontend fitfunction object classes don't explicitly store their units.  Many don't even have a 'units' slot. An MxFitFunctionML can have units of "-2lnL" or "Pr", depending on which expectation class it's working with, and on the value of its 'vector' slot.  And MxFitFunctionMultigroup seems completely agnostic with regard to units--I'm not sure it would stop you if you used it in an instance where one group is using the ML fitfunction and the other group is using a WLS fitfunction.

As an aside, the unit labels that our backend recognizes are "-2lnL", "Pr", "r'Wr", "?", and "", but this is not documented anywhere in the man pages, and I'm not even sure all of those are valid choices for the user when s/he can select the units, as with MxFitFunctionAlgebra or MxFitFunctionR.

Here's a tentative proposal: make a 'units' slot part of the base fitfunction class, and have the backend export a units label to the frontend fitfunction?

**Comment by mcneale** [comment]
That's good, but one might deliberately mix fit functions I suppose. Reml and ML might examine whether h2 was significantly missing.  Slot is good idea.  I figure any algebra or hybrid function should be rendered unknown unless explicitly declared as e.g. -2lnL - reminisced of option ISCHI in classic.

We likely need some safety nets for user blunders, as ever.

Cheers
Mike

Sent from my iPhone

On Sep 6, 2017, at 6:22 PM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to make headway on this issue today. It's going to be a little more tricky that I first thought, because most frontend fitfunction object classes don't explicitly store their units. Many don't even have a 'units' slot. An MxFitFunctionML can have units of "-2lnL" or "Pr", depending on which expectation class it's working with, and on the value of its 'vector' slot. And MxFitFunctionMultigroup seems completely agnostic with regard to units--I'm not sure it would stop you if you used it in an instance where one group is using the ML fitfunction and the other group is using a WLS fitfunction.

As an aside, the unit labels that our backend recognizes are "-2lnL", "Pr", "r'Wr", "?", and "", but this is not documented anywhere in the man pages, and I'm not even sure all of those are valid choices for the user when s/he can select the units, as with MxFitFunctionAlgebra or MxFitFunctionR.

Here's a tentative proposal: make a 'units' slot part of the base fitfunction class, and have the backend export a units label to the frontend fitfunction?

**Comment by RMKirkpatrick** [comment]
I'd at least like input from @jpritikin before I start making changes to the fitfunction API.

Maybe we should discuss this as a team during the meeting tomorrow?

**Comment by jpritikin** [comment]
Do we need backend changes? Isn't `model$output$fitUnits` available?

**Comment by RMKirkpatrick** [comment]
Aha!  The fit units are in the output!  I didn't realize that.  That should make things a lot simpler.

**Comment by RMKirkpatrick** [comment]
[a2d9412](https://github.com/OpenMx/OpenMx/commit/a2d9412d0c6920333ce734a386c0f8a7b00d260d)  adds comparison-validity checks to the `mxCompare()` code.  Comparing two models that have non-matching, non-NULL fit units is an error.  For now, comparing a model using the GREML fitfunction to a model using any other fitfunction is an error, but if we give the GREML fitfunction its own REML fit units as discussed during the meeting today, this check will be redundant.  Comparing two models using a GREML expectation but with different names for the fixed effects is a warning, since mismatching variable names doesn't guarantee that the two models are actually using different regressors.

I'll still need to make similar changes to `mxCompareMatrix()`.

**Comment by RMKirkpatrick** [comment]
[fc068db](https://github.com/OpenMx/OpenMx/commit/fc068db7ccfea79e4c96d3a3c2a8c432533008f2) moves the comparison-validity checking from the main body of `mxCompare()` to the code for an internal function, `collectStatistics1()`.  This effectively implements the checks for `mxCompareMatrix()` as well.
