### ISSUE TITLE
npsol download links missing?

### ISSUE THREAD

**Issue by khusmann** [OpenMx/OpenMx#258]
Hello, I am trying to compile OpenMx on linux using the getOpenMx.R script.

It appears that it's unable to find the download link for libnpsol.a. I get this error:

```
************ ************
WARNING: Cannot verify correct libnpsol.a version
sha1sum libnpsol.a => 446a0b9731564bbb190158e83eefcb15f6307632
************ ************
```

That sha1sum applies to a download of the directory listing html file of `http://openmx.ssri.psu.edu/software/packages/npsol/linux/x86_64/`

I'm running gcc 7.3.0

Thanks for your help!

**Comment by jpritikin** [comment]
Try `https://vipbg.vcu.edu/vipbg/OpenMx2/software//packages/npsol/linux/x86_64/947c218861254b5737a91c61c8d8ed82684e413f` (for gcc 7.2).

Download this file and rename it to src/libnpsol.a

If it works then we'll add it to the list.

**Comment by khusmann** [comment]
Thanks for the reply! It compiles/links alright in gcc7.3, but then when trying to use it I get: 

```
 *** caught segfault ***
address 0xae8250050, cause 'memory not mapped'
```
Strangely, when I try it on a different machine with gcc7.4, it works fine. Seems like one of those scary undefined behavior things when swapping library ABIs.

After reading a bit more about the optimizers it looks like CSOLNP works just as fast as NPSOL (https://www.ncbi.nlm.nih.gov/pubmed/28535831); I had started down this path under the impression NPSOL might have better performance. 

Is there any reason to use NPSOL or does CSOLNP completely supersede it?

**Comment by jpritikin** [comment]
> Is there any reason to use NPSOL or does CSOLNP completely supersede it?

It is difficult to say which optimizer performs better. For unconstrained problems, there is probably little difference. For constrained problems, SLSQP might offer better performance than either NPSOL or CSOLNP.

**Comment by RMKirkpatrick** [comment]
> Thanks for the reply! It compiles/links alright in gcc7.3, but then when trying to use it I get:
> 
> ```
>  *** caught segfault ***
> address 0xae8250050, cause 'memory not mapped'
> ```
> 
> Strangely, when I try it on a different machine with gcc7.4, it works fine. Seems like one of those scary undefined behavior things when swapping library ABIs.

Odd.  Out of curiosity, what BLAS does `sessionInfo()` in R say you're using?

> 
> After reading a bit more about the optimizers it looks like CSOLNP works just as fast as NPSOL (https://www.ncbi.nlm.nih.gov/pubmed/28535831); I had started down this path under the impression NPSOL might have better performance.
> 
> Is there any reason to use NPSOL or does CSOLNP completely supersede it?

It's undeniably true that NPSOL and CSOLNP (and SLSQP) differ in their effectiveness at solving different optimization problems, but it's extremely difficult to predict which of the 3 is the best choice for a given problem.  Almost every rule of thumb I've tried to formulate for choosing among the 3 based on the problem's characteristics has had too many exceptions to be trustworthy.  The only comparisons I'm confident in are as follows:

1. As reported in the CSOLNP paper you linked, we have empirical evidence that CSOLNP is the best first choice for unconstrained analyses of ordinal-threshold data.
2.  The lead author on [a recent preprint](https://arxiv.org/abs/1911.09939) chose to use CSOLNP based on a simple simulation showing CSOLNP had the best convergence rates for fitting bilinear-spline growth mixture models.
3.  On theoretical grounds, SLSQP is the best first choice for the confidence-limit search.  That's why it's the default for [`omxRunCI()`](https://openmx.ssri.psu.edu/docs/OpenMx/latest/_static/Rdoc/omxParallelCI.html).
4.  Only NPSOL can cope with the general case of [linearly dependent equality constraints](https://github.com/OpenMx/OpenMx/issues/99).

**Comment by khusmann** [comment]
@RMKirkpatrick Thanks for the reply and the info on the optimizer! Here's my sessionInfo():

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.10 (Santiago)

Matrix products: default
BLAS/LAPACK: /home/<user>/conda/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1
```

**Comment by RMKirkpatrick** [comment]
OK.  I thought I might have an idea why it segfaulted, but now I don't think I do.
