### ISSUE TITLE
Add argument to mxDataWLS for all-continuous means

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#26]
All-continuous data do not include means for weights for the means.

This should add a switch to mxDataWLS to compute the weights in the ordinal/joint way vs in the all-continuous way.

Perhaps call the argument `allContinuousMethod`.  It takes string values 'cumulants' and 'marginal'.  It defaults to 'cumulants'.

**Comment by mcneale** [comment]
'cumulants' preferably... but otherwise fine.

Cheers
Mike

From iPad - brief

Michael C. Neale, Ph.D.
Professor, Departments of Psychiatry & Human Genetics
Virginia Commonwealth University  VIPBG
Shipping Address: 800 East Leigh St. Suite 1-114, Richmond VA 23219-1534
Mailing Address : Box 980126 MCV Richmond VA 23298-0126
Telephone: (804) 828-3369  Fax: (804) 828-1471 Email: neale@vcu.edu<mailto:neale@vcu.edu>

On Sep 8, 2017, at 9:42 AM, Michael Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


All-continuous data do not include means for weights for the means.

This should add a switch to mxDataWLS to compute the weights in the ordinal/joint way vs in the all-continuous way.

Perhaps call the argument allContinuousMethod. It takes string values 'cummulants' and 'marginal'. It defaults to 'cummulants'.

**Comment by mhunter1** [comment]
Gah!  Updated.

**Comment by mhunter1** [comment]
9ae8c9db53531ff6cc255b9eb473df43fb37eb1c
