### ISSUE TITLE
complain about lbound and ubound equal

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#269]

**Comment by RMKirkpatrick** [comment]
It should also complain if lbound is greater than ubound.

**Comment by RMKirkpatrick** [comment]
See the attached script, which fits a model when a free parameter has an equal lbound and ubound.  CSOLNP quits at the start values, and OpenMx warns about status code 6.  NPSOL, SLSQP, and Nelder-Mead all reach solutions with status code 5 or 6, but that solution is the correct solution for the case when the free parameter in question is fixed equal to the bound (see `factorModelFit4`).

It would be good for OpenMx to at least warn about the case of equal lbound and ubound.

[200211--equal_l&ubounds.R.txt](https://github.com/OpenMx/OpenMx/files/4320060/200211--equal_l.ubounds.R.txt)

**Comment by RMKirkpatrick** [comment]
In the case of an lbound being greater than the parameter's ubound, CSOLNP tries to adjust the free parameter in question, but otherwise quits at the start values, with code 6.  SLSQP and NPSOL both give errors.  Nelder-Mead does the best it can, and prevents the free parameter from ever crossing either bound. But, its solution has status code 5...which, now that I think about it, might not be correct, since the Hessian does not have to be PD at the solution when bounds are active.

[200211--backwards_bounds.R.txt](https://github.com/OpenMx/OpenMx/files/4320092/200211--backwards_bounds.R.txt)

**Comment by RMKirkpatrick** [comment]
lbound and ubound equal warrants a warning to point it out, I would think.  The user is probably going to see a status Red at any rate, because having equal lbound and ubound make the parameter effectively fixed, but OpenMx believes it is free.

lbound greater than ubound currently causes both NPSOL and SLSQP to raise errors.  It should probably raise an error with CSOLNP as well.  Should it always be an error?

**Comment by jpritikin** [comment]
> Should it always be an error?

Yeah, I think so.

This should be easy to fix. Let's try to address this can get the issue closed.

**Comment by mcneale** [comment]
Two options here: 
1. raise an error and make the hapless user fix it themselves
2. automatically fix that parameter, and tell the user that that is what we did and why
I think users might prefer choice 2, as we can assume that they're busy or lazy

**Comment by RMKirkpatrick** [comment]
During the meeting today, we agreed that the case of lbound >= ubound should raise a fatal error.
