### ISSUE TITLE
increase mxOption maxOrdinalPerBlock

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#300]
Had a user stymied by 
> The job for model 'ACE' exited abnormally with the error message: Ordinal covariance has dependent block larger than 20x20. You must increase mxOption maxOrdinalPerBlock

Would be great to say what size the dependent block found was, and say: 
> . You must increase the maximum block size, e.g. `mxOption(m1, key = "maxOrdinalPerBlock", value=value_found)`

But if the user *must* do it, why not just override/set the block size to the value needed for this model for them? 

There's no other way to run the model, and they know it's a slow multivariate ordinal model. But they have no idea what block sizes, or mxOption key values are.

Be good too to point to documentation of what ordinal blocks in the error, if it is retained?

**Comment by mcneale** [comment]
It's mostly because it's a hopeless analysis.  It will take too long to evaluate the integrals - and they will probably be too inaccurate for model fitting.  So it is helpful to have a fence to let the user know that they are optimizing off-piste and at their own risk if they choose to jump the fence.

**Comment by jpritikin** [comment]
What @mcneale said, but I like your idea to improve the error message. See v2.18.1-150-gf9bef760c

**Comment by tbates** [comment]
Thanks! Researcher groks the new advice...,model running....
