### ISSUE TITLE
Allow tibble in MxData

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#345]
Allow the `observed` argument of `mxData()` to be a tibble by casting to a `data.frame` with `as.data.frame()`.  Otherwise, users get a cryptic error message.  See: https://openmx.ssri.psu.edu/comment/9559#comment-9559

**Comment by tbates** [comment]
Isn't what's needed a check on the construction side so that a tribble is turned into a dataframe when ingested?

You're right `is.data.frame(tibble)` is TRUE, but `class(tmp)[[1]]` reveals the culprit "tbl_df" without needing `tibble` code in OpenMx. 

Then just `as.data.frame()` – that way it will have the expected class and not be turned into a vector behind the user's back if they were relying on tibble's to prevent that R-ism.

```R
a = 1:5; tmp = tibble(a, a * 2)
is.data.frame(tmp) # TRUE
class(tmp)
```
> [1] "tbl_df"     "tbl"        "data.frame"

**Comment by mhunter1** [comment]
> Isn't what's needed a check on the construction side so that a tribble is turned into a dataframe when ingested?

No.  The tibbles passed through OpenMx fine in almost all cases without any special handling.  There was only a bug when data from a tibble was used as a definition variable.  In that case, OpenMx evaluated `theData[arow, acol]` in the frontend.  When `theData` was a tibble, this evaluated to a tibble because its default `[` operator has `drop=FALSE`; whereas `data.frame`s have `drop=TRUE`.  The minimal change was to get the scalar output OpenMx needed by explicitly setting `drop=TRUE`.  We did NOT need all the extra overhead of changing the tibbles to `data.frame`s.

**Comment by tbates** [comment]
Cool: glad it was that simple.
