### ISSUE TITLE
Cannot use mxRun(model, unsafe=T) within mxTryHardOrdinal

### ISSUE THREAD

**Issue by mcneale** [OpenMx/OpenMx#368]
The issue we face presently is that we get no output object back at all from mxTryHardOrdinal when it encounters an error such as a singular matrix at current estimates.  With mxRun(model, unsafe=T) you do get the object back, and it can be critically important in debugging the issue with the model.  Substituting one mxRun() does not get to the same place as mxTryHardOrdinal, so that isn't informative either.  I guess that this is the case for mxTryHard as well.

Solution would seem to be to allow ... arguments to mxTryHardOrdinal.

**Comment by RMKirkpatrick** [comment]
The premise of this issue is incorrect on two counts.  First, _every_ call to `mxRun()` within `mxTryHard()` has used argument `unsafe=T` since 29bf85d (April 2019).  Second, `mxTryHardOrdinal()` has _always_ accepted `...`, ever since it was first created in ea3988e (February 2016).

Setting aside those two points, this,

> The issue we face presently is that we get no output object back at all from mxTryHardOrdinal when it encounters an error such as a singular matrix at current estimates. With mxRun(model, unsafe=T) you do get the object back, and it can be critically important in debugging the issue with the model.

, seems to be the core of this issue...?  Yes, it is true that `mxTryHard*()` does not return failed fit attempts.  I cannot see much informational value in it doing so.

I'm going to close this issue.  If anyone can clearly describe the alternative `mxTryHard*()` behavior @mcneale seems to have in mind, either re-open and appropriately re-title this issue, or (preferably) open a new issue.
