### ISSUE TITLE
Extend `mxCheckIdentification()` for definition variables

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#386]
This is going to be a multistep process:
* `mxCheckIdentification()` is in R/MxExpectationNormal.R
* Find all definition variables.  Needs to happen by variable name and by dataset (possibly multiple data objects in a model).
* Write function to find what all the definition variables are
* Change all definition variables to free parameters
* Some definition variables occur in matrices.
* Some occur in algebras.
* The definition variables in algebras can be converted to 1x1 matrices as in R/MxAlgebraConvert.R and the function `insertDefinitionVariable()`.
* This generally may need to to a lot of the same processing that is currently done in mxRun().
* Add argument `defvar.row` to `mxCheckIdentification()`.
* Make sure this argument is passed through to omxModelByParameterJacobian() and the constraint function.
* Document special behavior of `defvar.row`.  Takes a single numeric value, or a function that chooses definition variable rows.
* Write function to choose definition variable rows.  25th percentile of each variable.  When another value is needed add the 75th percentile (or the next higher value that is distinct from the first value).
* definitionStartingValue in R/DefinitionVars.R
* What happens if there are definition variables in multiple groups?  X1 in group 1, X2 in group 2.  No assurance that X1 and X2 have the same number of rows or that rows align such that a correlation between X1 and X2 is meaningful.  Maybe assume X1 and X2 are correlated 0?

**Comment by mcneale** [comment]
Cool!  Some observations noted

On Feb 11, 2024, at 10:49 AM, Michael Hunter ***@***.***> wrote:


This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/JqxBPMk!llOjrVxo-zBbsVuX23FMbBDcRxkGuo-Kmuc37Z8YEGoum0yHTOFTx9E4Ocx7kLE1peBi8L9gV383Y8fiu1E7$>
Report Suspicious


This is going to be a multistep process:

  *   mxCheckIdentification() is in R/MxExpectationNormal.R
  *   Find all definition variables. Needs to happen by variable name and by dataset (possibly multiple data objects in a model).
  *   Write function to find what all the definition variables are
  *   Change all definition variables to free parameters

Should we have a reserved name for such changes?  And we need a way to change them back again.

  *   Some definition variables occur in matrices.
  *   Some occur in algebras.
  *   The definition variables in algebras can be converted to 1x1 matrices as in R/MxAlgebraConvert.R and the function insertDefinitionVariable().
  *   This generally may need to to a lot of the same processing that is currently done in mxRun().
  *   Add argument defvar.row to mxCheckIdentification().
  *   Make sure this argument is passed through to omxModelByParameterJacobian() and the constraint function.
  *   Document special behavior of defvar.row. Takes a single numeric value, or a function that chooses definition variable rows.
  *   Write function to choose definition variable rows. 25th percentile of each variable. When another value is needed add the 75th percentile (or the next higher value that is distinct from the first value).
  *   definitionStartingValue in R/DefinitionVars.R
  *   What happens if there are definition variables in multiple groups? X1 in group 1, X2 in group 2. No assurance that X1 and X2 have the same number of rows or that rows align such that a correlation between X1 and X2 is meaningful. Maybe assume X1 and X2 are correlated 0?

I’m generally leery of assumptions.  Definition variables in different groups may be effectively independent since there may entirely different variables from different people.  Not sure otherwise.

**Comment by mhunter1** [comment]
Note that the actual method differs from the proposed plan, but it correct.

**Comment by RMKirkpatrick** [comment]
Nice work, @mhunter1 !
