### ISSUE TITLE
omxReadGRMBin.R

### ISSUE THREAD

**Issue by RPorneso** [OpenMx/OpenMx#392]
I saw this was written by GCTA guys Jiang Yang and Robert Kirkpatrick but I thought I'd send this to you instead since the code seems to be part of the openMX package. I'm also not sure if this is really bug but I'd put it out here anyway, just in case other people have experienced the same "issue", which is relatively quite easy to solve. 

The dimnames arg on line 48 results in an error if your ID is non-numeric. Removing that arg resolves the issue for me but perhaps there is a cleaner way to do this. 

<img width="889" alt="image" src="https://github.com/user-attachments/assets/6acc5ca2-0519-407e-8200-e0e3060c3c13">

Feel free to simply close this issue if it's a non issue. Thank you.

**Comment by RMKirkpatrick** [comment]
Well, I'm not a GCTA developer, but I did adapt Jiang Yang's code into the function to which you refer.

You're correct that the function does assume that family ID and individual ID are both numeric, and that that assumption leads to problems when the IDs are, say, character strings.

Your workaround does get the function working with non-numeric IDs, but the GRM ought to have dimnames nonetheless, so that the user can do such things as verify that participants' rows of the dataset correspond to their rows and columns in the GRM.  The function should probably condition its behavior based on the data type of the IDs.  Numeric IDs can be added together; character IDs can be adhered, with a "_" or "." separating family ID from individual ID.

Thanks for bringing this matter to my attention.  I will bring it up at the next OpenMx developers' meeting.

**Comment by RMKirkpatrick** [comment]
Resolved with d4aa93e.  The function now always creates dimnames by `paste()`ing family and individual IDs, separated with an underscore.
