### ISSUE TITLE
row diagnostics are all zero

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#53]
The `rowDiagnositcs` argument to `mxFitFunctionML` returns a vector of all zeros in OpenMx 2.9.4.  The feature was not heavily tested: only checking that the vectors of row likelihoods from two different models were the same in e.g. `inst/models/passing/StateSpaceAlg.R`.  It is also checked that it does not throw an error in the man page for `mxFitFunctionML`.  Below is a script, the last line of which should give the first several row likelihoods, but currently gives all zeros.

```
library(OpenMx)

# Simulate some data
x=rnorm(1000, mean=0, sd=1)
y= 0.5*x + rnorm(1000, mean=0, sd=1)
tmpFrame <- data.frame(x, y)
tmpNames <- names(tmpFrame)

# Define the matrices
M <- mxMatrix(type = "Full", nrow = 1, ncol = 2, values=c(0,0), 
              free=c(TRUE,TRUE), labels=c("Mx", "My"), name = "M")
S <- mxMatrix(type = "Full", nrow = 2, ncol = 2, values=c(1,0,0,1), 
              free=c(TRUE,FALSE,FALSE,TRUE), labels=c("Vx", NA, NA, "Vy"), name = "S")
A <- mxMatrix(type = "Full", nrow = 2, ncol = 2, values=c(0,1,0,0), 
              free=c(FALSE,TRUE,FALSE,FALSE), labels=c(NA, "b", NA, NA), name = "A")
I <- mxMatrix(type="Iden", nrow=2, ncol=2, name="I")

# Define the expectation
expCov <- mxAlgebra(solve(I-A) %*% S %*% t(solve(I-A)), name="expCov")
expFunction <- mxExpectationNormal(covariance="expCov", means="M", dimnames=tmpNames)

# Choose a fit function
fitFunction <- mxFitFunctionML(rowDiagnostics=TRUE)
# also return row likelihoods, even though the fit function
#  value is still 1x1

# Define the model
tmpModel <- mxModel(model="exampleModel", M, S, A, I, expCov, expFunction, fitFunction, 
                    mxData(observed=tmpFrame, type="raw"))

# Fit the model and print a summary
tmpModelOut <- mxRun(tmpModel)
summary(tmpModelOut)

fitResOnly <- mxEval(fitfunction, tmpModelOut)
attributes(fitResOnly) <- NULL
fitResOnly

# Look at the row likelihoods alone
fitLikeOnly <- attr(mxEval(fitfunction, tmpModelOut), 'likelihoods')
head(fitLikeOnly)
```

**Comment by jpritikin** [comment]
To make this work, the code would need to be more complex. Instead of fixing it, can we remove the option and suggest that people use vector=TRUE instead?

**Comment by mhunter1** [comment]
That's not really so much a solution as a decision to no longer have this feature.

**Comment by jpritikin** [comment]
Oh, I see you added the capability in v2.1.0-182-g9331c69a5. How do you feel about discontinuing the feature?

**Comment by mhunter1** [comment]
Having implemented the feature myself, I'm not keen on it disappearing.  Neither do I like the number of features of OpenMx going down.  Moreover, it was a a feature of classic Mx.  For some time there have been plans to _extend_ this feature to include Mahalanobis distances along with the number of observed variables to make a mixture of chi-square residuals QQ plot for outlier detection.

**Comment by jpritikin** [comment]
> Having implemented the feature myself, I'm not keen on it disappearing.

Understandable. I hesitate because it's so similar to `vector=TRUE`. For example, the sufficient statistic optimization would need to be disabled in both situations.

> For some time there have been plans to extend this feature to include Mahalanobis distances along with the number of observed variables to make a mixture of chi-square residuals QQ plot for outlier detection.

Wouldn't that feature make sense in the context of `vector=TRUE`?

**Comment by mhunter1** [comment]
The feature could be implemented as adding a single compute step with `vector=TRUE` at the end of optimization.

**Comment by mcneale** [comment]
The trouble I had with vector=TRUE was that it’s difficult to redo the whole fitting function just to be able to see the residuals.  Especially if it’s multi group.   If they are always available without reconfiguring the model, so much the better.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Mar 9, 2018, at 12:41 PM, Joshua Pritikin <notifications@github.com<mailto:notifications@github.com>> wrote:


Having implemented the feature myself, I'm not keen on it disappearing.

Understandable. I hesitate because it's so similar to vector=TRUE. For example, the sufficient statistic optimization would need to be disabled in both situations.

For some time there have been plans to extend this feature to include Mahalanobis distances along with the number of observed variables to make a mixture of chi-square residuals QQ plot for outlier detection.

Wouldn't that feature make sense in the context of vector=TRUE?

**Comment by jpritikin** [comment]
Good point. See v2.9.4-23-g4ff9e9b63
