### ISSUE TITLE
Build error: ‘typeof’ was not declared in this scope

### ISSUE THREAD

**Issue by ZoeReed** [OpenMx/OpenMx#55]
Hi, 

There appears to be a build error on the stable branch when trying to install this on a linux machine, as follows:
```

omxFIMLFitFunction.cpp: In member function ‘virtual void omxFIMLFitFunction::invalidateCache()’:
omxFIMLFitFunction.cpp:820:48: error: ‘typeof’ was not declared in this scope
omxFIMLFitFunction.cpp:820:49: error: template argument 1 is invalid
omxFIMLFitFunction.cpp: In member function ‘virtual void omxFIMLFitFunction::init()’:
omxFIMLFitFunction.cpp:1050:56: error: ‘typeof’ was not declared in this scope
omxFIMLFitFunction.cpp:1050:57: error: template argument 1 is invalid
make[1]: *** [omxFIMLFitFunction.o] Error 1
make[1]: Leaving directory `/panfs/panasas01/sscm/zr15964/OpenMx/src'
ERROR: compilation failed for package ‘OpenMx’
* removing ‘/tmp/Rtmpps0oZm/devtools_install_4338205c1876/OpenMx’
Error: Command failed (1)
Execution halted
make: *** [install] Error 1
```

I used the folllowing commands to try and do this:
```
git clone https://github.com/OpenMx/OpenMx.git
cd OpenMx/
git checkout stable
make install
```

Many thanks

**Comment by jpritikin** [comment]
Ensure '-std=gnu++11' appears in CC, CXX, CXX1X, and CXX11.

**Comment by RMKirkpatrick** [comment]
@jpritikin You mean in the Makeconf file, correct?

**Comment by jpritikin** [comment]
On Linux, I typically modified these variables in `$HOME/.R/Makevars`

**Comment by ZoeReed** [comment]
Thank you, that seems to work

**Comment by apascualgarcia** [comment]
@jpritikin could you please elaborate the answer? I'm getting the same error
installing OpenMx from the R prompt with: 

`source('https://openmx.ssri.psu.edu/software/getOpenMx.R')` 

and, apparently, the above flag is included because the last compilation line is:

`g++ -std=c++11 -I/usr/share/R/include -DNDEBUG   -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.2/RcppEigen/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.2/StanHeaders/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.2/BH/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.2/rpf/include"  -fopenmp     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c omxFIMLFitFunction.cpp -o omxFIMLFitFunction.o`

that returns:

`omxFIMLFitFunction.cpp: In member function ‘virtual void mxFIMLFitFunction::invalidateCache()’: 
omxFIMLFitFunction.cpp:821:48: error: ‘typeof’ was not declared in this scope`  

`rowCount = std::numeric_limits<typeof(rowCount)>::max();
                                                ^`

`omxFIMLFitFunction.cpp:821:49: error: template argument 1 is invalid 
rowCount = std::numeric_limits<typeof(rowCount)>::max();
                                                 ^`

`omxFIMLFitFunction.cpp: In member function ‘virtual void omxFIMLFitFunction::init()’: omxFIMLFitFunction.cpp:1057:56: error: ‘typeof’ was not declared in this scope
  newObj->rowCount = std::numeric_limits<typeof(rowCount)>::max();
                                                        ^
omxFIMLFitFunction.cpp:1057:57: error: template argument 1 is invalid 
 newObj->rowCount = std::numeric_limits<typeof(rowCount)>::max();`

Thanks in advance

**Comment by mcneale** [comment]
Hi Alberto. 

Looks like yours says g++ -std=c++11 whereas it should be g++ -std=gnu++11 according to Joshua.

**Comment by jpritikin** [comment]
Yeah, the typeof stuff is presently a gnu extension. But I believe it is accepted for the next standards update.

**Comment by apascualgarcia** [comment]
Ups, many thanks, I didn't realize, I've been able to compile it now.  In any case, I'm thinking that if this flag is not the default one in R I guess that users installing OpenMx directly from R (or rstudio in my case) will face the same problem, and probably some of them will not be familiar with compilation flags, etc. So do you want me to open a documentation issue to ask for an explanation on how this issue is solved this in the website installation instructions? I'm not an R developer and it took me a while to learn how things are organized.
