### ISSUE TITLE
Improve the documentation for as.statusCode

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#64]
Give interpretations that are interpretable by mere mortals.  If a status code is triggered, point to the help help that describes these and gives suggestions for what to do.

**Comment by tbates** [comment]
Let's iterate over some improvements here's some starters:

0,‘OK’: Good news. Optimization succeeded.

1,‘OK/green’: The solution couldn't be improved and is likely to be good. However, you might want to run m1 = mxTryHard(m1) to be sure. Technically, Optimization succeeded, but terminated because no further improvement could be made rather than because the iterations converged. NPSOL was  (Mx status GREEN). 

2,‘infeasible linear constraint’: Hmm. I have not yet been told how to explain this to mortal users or what you can do about it. Technically, the linear constraints and bounds could not be satisfied. The problem has no feasible solution.

3,‘infeasible non-linear constraint’: Hmm. I have not yet been told how to explain this to mortal users or what you can do about it. Technically, the nonlinear constraints and bounds could not be satisfied. The problem may have no feasible solution.

4,‘iteration limit’: I ran out of time running this model. You might want to rerun: m1 = mxRun(m1) or m1 = mxTryHard(m1). Technically, the major iteration limit was reached (Mx status BLUE).

5,‘not convex’: Hmm: I don't trust this solution. My only suggestion is run m1 = mxTryHard(m1). Technically, the Hessian at the solution does not appear to be convex (Mx status RED). See https://en.wikipedia.org/wiki/Hessian_matrix

6,‘nonzero gradient’: Hmm: I don't trust this solution. My only suggestion is run m1 = mxTryHard(m1). Technically, the model does not satisfy the first-order optimality conditions to the required accuracy, and no improved point for the merit function could be found during the final linesearch (Mx status RED)

7,‘bad deriv’: Hmm. I have not yet been told how to explain this to mortal users or what you can do about it. Technically, the function derivates returned by funcon or funobj seem incorrect.

9,‘internal error’: Hmm. I have not yet been told how to explain this to mortal users or what you can do about it. Technically, an input parameter was invalid.

10,‘infeasible start’: Bad news, I couldn't run your model: I need you to modify the start values for one or more parameters. For instance, set means to their measured value, or set variances and covariances to plausible values. Technically, the starting values were infeasible.

**Comment by jpritikin** [comment]
Alright, I pushed v2.9.6-82-gef020c2e4 with some improvements.

Code 2/3 typically indicate that the model is ill-posed. So maybe just use colloquial language, "Your model specification is bad." ?

**Comment by tbates** [comment]
@jpritikin, maybe:

2,‘infeasible linear constraint’: Hmm. Typically, this error suggest that the model specification is bad. You might try m1 = mxTryHard(m1), but more likely there's an error in your model script. Technically, the linear constraints and bounds could not be satisfied. The problem has no feasible solution.

3,‘infeasible non-linear constraint’: Hmm. Typically, this error suggests that the model specification is bad. You might try m1 = mxTryHard(m1), but more likely there's an error in your model script. Technically, the nonlinear constraints and bounds could not be satisfied. The problem may have no feasible solution.

**Comment by mcneale** [comment]
I would say "The problem appears to have no solution where the constraints are satisfied" and instead of "but more likely there's an error in your model script." I would say "as it's possible the starting values are bad (try to start somewhere that the constraints are satisfied, if possible).  In any case, it seems there's something inconsistent about the constraints you have specified."  My aim here is to avoid the very generic "there's something wrong with your script"

3,‘infeasible non-linear constraint’: Hmm. Typically, this error suggests that the model specification is bad. You might try m1 = mxTryHard(m1), as the starting values may be very bad (try to start somewhere that the constraints are satisfied, if possible).  In any case, it seems there's something inconsistent about the constraints you have specified.  Technically, we say the nonlinear constraints and bounds could not be satisfied. The problem may have no feasible solution.

It would be nice if we could identify which constraints are the culprit - rather like which parameters  are the likely problem with under-identification (something that we might be able to figure out from eigenvalues of the Hessian but afaik we don't actually do).

**Comment by RMKirkpatrick** [comment]
FWIW, I don't think it's currently possible for OpenMx to return status code 2, since we treat all MxConstraints as nonlinear.

**Comment by tbates** [comment]
did these last two improved errors from Mike get done? if  so could close this issue

2,‘infeasible linear constraint’: The problem appears to have no solution where the constraints are satisfied. It's possible the starting values are bad (try to start somewhere that the constraints are satisfied, if possible). In any case, it seems there's something inconsistent about the constraints you have specified.

3,‘infeasible non-linear constraint’: Hmm. Typically, this error suggests that the model specification is bad. You might try m1 = mxTryHard(m1), as the starting values may be very bad (try to start somewhere that the constraints are satisfied, if possible). In any case, it seems there's something inconsistent about the constraints you have specified. Technically, we say the nonlinear constraints and bounds could not be satisfied. The problem may have no feasible solution.
